# Generated by Django 5.2 on 2025-04-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.CharField(max_length=50)),
                ('terrains', models.TextField()),
                ('climates', models.TextField()),
            ],
        ),
    ]
